alter session set current_schema=cr_app_admin;
set serveroutput on;

-- Add new insurance type
EXEC add_insurance_type('VJ special', 30000);

-- update existing insurance type
-- update_insurance_type (pi_insurance_type_name VARCHAR2, pi_new_coverage NUMBER)
EXEC update_insurance_type('VJ special', 10000);


-- View analytics about revenue generated by insurance types
select * from view_insurance_res_rev;

-- View analytics about preferred insurance types by vehicle type
select * from view_insurance_top_performer;
